_ext/jboss_developer.rb
Working on getting all the 404s corrected. Trying to build links to
github if we don't have them in the site.
=> DEVELOPER-1160 quickstart 404 links

products/eap/_common/product.yml
=> DEVELOPER-1184 Added in EAP 6.4 Alpha to be displayed on the main site

Gemfile, Gemfile.lock, Rakefile
I've tried with this setup for an hour, rebuilding seems to be working
fine. I made multiple changes to book.js file and they all worked
exactly as I expect them to. I did this off and on for over an hour.
=> DEVELOPER-1190 (rebuilding the site)

_config/site.yml
=> PERF TESTING DEVELOPER-1189 Okay to merge

_config/docker_images.yml
Only thing that could be wrong is that logo references apiman site, instead of static.jboss.org sites for images, but I do not know how to add image there.
http://www.apiman.io/latest/resources/images/apiman_logo_200x150.png
=> apiman docker image

buzz.html.slim
Simply removed the search result div, doesn't seem to hurt anything,
solves the issue.
=> Fixes DEVELOPER-1185

products/eap/_common/product.yml
If any changes need to be made, please let me know.
=> DEVELOPER-1206 Added in EAP 6.4.0.Beta to the product downloads

_dcp/data/query/product_forum_activity.json
Relevant to upgrade to Searchisko 2.0.0
=> Add product_forum_activity query.

events.html.slim, stylesheets/_events.scss
I kind of hacked the css together to make the shadowman appear closer to "RED HAT EVENTS".  It seems to scale okay when resizing the screen.
=> DEVELOPER-1187 Red Hat events is now displaying the shadowman logo

_partials/product-connectors-item.html.slim, javascripts/connectors.js
For testing at this point.  Let me know how this should be changed.  I updated the partial to display the links and the js hides if it is an empty string.
=> DEVELOPER-1210 Ability to add URLs to collateral for each connector

Gemfile, Gemfile.lock
Fixes are all in aweplug, see related commit:
LightGuard/aweplug:DEVELOPER-1203
=> Update to aweplug branch for DEVELOPER-1203 (Google Books)

_config/docker_images.yml
* updated the AeroGear project des.
* putting in the new Docker images for AeroGear (UnifiedPush Server (WildFly based) and SimplePush (Netty based)
=> Adding new AeroGear Docker images

javascripts/buzz.js
Kind of a hacked fix, but it fixes the off by one issue
=> DEVELOPER-1243 Fixed Buzz.js off by one on the dcp query for results.

_layouts/ticket-monster.html.slim, ticket-monster.adoc
Updated TicketMonster submodule commit hash, and link to PDF and items in ToC.
=> DEVELOPER-1227 Update to TicketMonster 2.7.0.Final

_partials/mini_buzz_template.html.slim
...and removed the  links from the author and date
=> DEVELOPER-1268 Fixed alignment of links in mini buzz template

Gemfile
For testing aweplug country code
=> DEVELOPER-1205 Removed the hard coding of the country variable and set it to an environment variable

_config/blinkr.yaml
=> DEVELOPER-810 - DO NOT MERGE - Updated Blinkr.yaml to ignore broken links that have JIRA tickets open.

_partials/getstarted-thankyou.html.slim, javascripts/terms-and-conditions.js, stylesheets/_get-started.scss
=> DEVELOPER-646 Official product downloads lack https URLs and checksums

Gemfile, Gemfile.lock
Aweplug pull request: https://github.com/awestruct/aweplug/pull/101
=> DEVELOPER-1241 READY FOR MERGE An error occurred: can't add a new key into hash during iteration

eclipse.html.slim
and adding co-lead for the CBI.
=> Fixing FireFox display issues for the project logos 

index.html.slim, spotlights.html.slim
This is for DEVELOPER-1320 and DEVELOPER-1322
=> Banner updates

devoxx4kids.html.slim
Requested by Arun Gupta. Needs to be approved first.
=> Adding Summit + DN CfP

javascripts/books.js, stylesheets/_books.scss
I don't know if this is the best fix, but it does seem to be a solution.  If it's not acceptable, let me know.
=> DEVELOPER-1323 Empty query on books page fails

_ext/stacks.rb
We lose the multi-threading, but this fixes the duplicate problem, also
gives us the correct ids for the boms as well. We'll need to clear the
DCP of boms and archetypes.
=> Fixing duplicate bom/archetype issue

_config/docker_images.yml
Docker image needs to be added first in:
https://registry.hub.docker.com/repos/jboss/
I didn't know how to build to verify so hopefully it will look good...
=> Adding Hawkular Docker image to the list

_layouts/mobile-terms-and-conditions.html.slim, mobile-terms-and-conditions.adoc
The microsite is in place for content
=> DEVELOPER-1349 HOLD Add Mobile Terms and Conditions Page

products/amq/_common/product.yml, products/fuse/_common/product.yml
The names for AMQ may need to be changed around.  I didn't know exactly what to name each of the items so this will need review.
=> Developer-1353 Downloads

.gitignore, _config/docker_images.yml
Docker image PR: https://github.com/jboss-dockerfiles/artificer/pull/2
=> Artificer Docker image

_config/site.yml, javascripts/namespace.js
Similar to https://github.com/redhat-developer/developers.redhat.com/pull/328
=> Prepare for migration to Searchisko v2.

javascripts/namespace.js, javascripts/projects.js
=> Use Searchisko v2 on "Upstream Projects" pages on jboss.org.

buzz.html.slim, javascripts/buzz.js
=> Use Searchisko v2 on "Buzz" pages on www.jboss.org.

products/devstudio/_common/product.yml
The short URL has now been added, so adding Installer with EAP back in
=> DEVELOPER-1371 - Added Installer with EAP

javascripts/namespace.js
Similar to https://github.com/redhat-developer/developers.redhat.com/pull/367
=> Add events search URL.

_layouts/get-started-item.html.slim
WIP - DEVELOPER-1377
DEVELOPER-1377 Fixed the broken link issue with the quickstart main pages
=> DEVELOPER-1377 Broken link pn product pages for Github

products/amq/_common/product.yml
The packages description "name" field is updated to match the section titles in the documentation as per JIRA https://issues.jboss.org/browse/FUSEDOC-821
=> changed the name of the packages

Gemfile.lock, _ext/jboss_developer.rb, _ext/pipeline.rb, _layouts/get-started-item.html.slim
Allows more than 1 target product for demos
=> Fixes DEVELOPER-1412

iot/index.html.slim
=> DEVELOPER-1417 - Added in Henryk's blogpost

products/eap/_common/product.yml
They added a few more things to add to the getting started guide.
=> DEVELOPER-1425 - Fixed the description and removed installer

_config/canonical.yml, _layouts/base.html.slim
Still need to add a way to customize the hrefs since not all of them will follow the convention that I added.  I am thinking about adding a field where you can customize the url where it will overwrite the default for each quickstart (just in case).
=> DEVELOPER-1423 - Added ability to reference canonical owner

iot/index.html.slim
=> DEVELOPER-1452 - Added in Henryk's blogpost

products/eap/_common/product.yml
Reverts jboss-developer/www.jboss.org#1011
=> Revert "DEVELOPER-1456 - Updated the download table for 7.0.0.Beta"

index.html.slim
=> Add SAMAS/SAMSAM ransome hero

index.html.slim
Removed old carousel slides and added the DevNation Live stream carousel.
=> Update JBoss Developers carousel.

index.html.slim
Update JBD carousel to add releases from DevNation.
=> DEVELOPER-3235 - Update carousel
